python train.py ^
--content_path "D:\nick\Desktop\jupyter notebook\styleTransfer\data\mydata\train\true_human" ^
--style_path "D:\nick\Desktop\jupyter notebook\styleTransfer\data\mydata\train\vango_human" ^
--name AdaAttN_with_edge ^
--model adaattn ^
--dataset_mode unaligned ^
--no_dropout ^
--load_size 256 ^
--crop_size 256 ^
--image_encoder_path ./checkpoints/vgg_normalised.pth ^
--gpu_ids 0 ^
--batch_size 1 ^
--n_epochs 12 ^
--n_epochs_decay 3 ^
--display_freq 1 ^
--display_port 8097 ^
--display_env AdaAttN ^
--lambda_local 2 ^
--lambda_global 10 ^
--lambda_content 0 ^
--lambda_edge 100 ^
--shallow_layer ^
--skip_connection_3 ^
--continue_train
