python train.py ^
--content_path "D:\MyProject\Dataset\coco2017\train2017" ^
--style_path "D:\MyProject\Dataset\wikiart" ^
--name artvggselfadaattnssloss_bicubic_adainloss2_allin ^
--model artvggselfadaattnssloss ^
--dataset_mode unaligned ^
--no_dropout ^
--load_size 256 ^
--crop_size 256 ^
--style_encoder_path ./checkpoints\artvgg19_2200_24class_with_norm/latest_net_artvgg.pth ^
--gpu_ids 0 ^
--batch_size 4 ^
--n_epochs 2 ^
--n_epochs_decay 3 ^
--display_freq 100 ^
--display_port 8097 ^
--display_env ArtvggSelfAdaAttN ^
--lambda_content 1 ^
--lambda_style 1 ^
--lambda_id1 50 ^
--lambda_id2 1 ^
--lr 0.0005 ^
--shallow_layer ^
--skip_connection_3 ^
--save_latest_freq 2000 ^
--data_norm

